filters:
  -
    name : domain_name
    value : coin

keys:
  -
    name: solvable
    values: 
      - True
      - False
  -
    name: search
    values:
      - bfs
      - bfsdc
      - bfsdcu
      - astar
      - greedy
  # -
  #   name: goal_size
  #   values:
  #     - 1
  #     - 2
  #     - 3
  

display_column_names:
  # - generated
  # - goal_checked
  # - epistemic_calls
  # - expanded
  # - pruned
  # - pruned_by_visited
  # - pruned_by_unknown
  - search_time
  - epistemic_call_time
